Repository quaquel/EMAworkbench, pull requests merged in 2022-10, with the labels that each got.

#189 Fix error for negative `n_processes` input in MultiprocessingEvaluator
  ema_workbench/em_framework/evaluators.py
Labels: bug

#193 Convergence tracking
  docs/source/indepth_tutorial/directed-search.ipynb
  ema_workbench/em_framework/__init__.py
  ema_workbench/em_framework/optimization.py
  ema_workbench/em_framework/util.py
  ema_workbench/examples/lake_model_dps.py
Labels: enhancement, feature

#150 optimization.py: Fix "epsilons" keyword argument in `_optimize()`
  ema_workbench/em_framework/optimization.py
Labels: bug, testing

#194 Improved directed search tutorial
  docs/source/indepth_tutorial/archives/0.tar.gz
  docs/source/indepth_tutorial/archives/1.tar.gz
  docs/source/indepth_tutorial/archives/2.tar.gz
  docs/source/indepth_tutorial/archives/3.tar.gz
  docs/source/indepth_tutorial/archives/4.tar.gz
  docs/source/indepth_tutorial/archives/archives.tar.gz
  docs/source/indepth_tutorial/directed-search.ipynb
  ema_workbench/__init__.py
  ema_workbench/examples/data/archives.tar.gz
  ema_workbench/examples/lake_model_intertemporal.py
Labels: docs

#200 Update Contributing.md with instructions how to merge PRs
  CONTRIBUTING.md
Labels: docs

#199 Update Readme with an introduction and documentation, installation and contribution sections
  README.md
Labels: docs

#184 Rhodium docs
  .gitignore
  CHANGELOG.md
  docs/source/changelog.md
  docs/source/getting_started/installation.rst
  docs/source/getting_started/other_packages.rst
  docs/source/getting_started/overview.rst
  docs/source/index.rst
Labels: docs

#206 release CI: pypa/gh-action-pypi-publish version
  .github/workflows/release.yml
Labels: ci, maintenance, ignore-for-release

#208 Make changelog work again
  .gitignore
  docs/source/conf.py
Labels: bug

#195 Fix spelling mistakes
  CHANGELOG.md
  CONTRIBUTING.md
  docs/source/basic_tutorial.rst
  docs/source/indepth_tutorial/directed-search.ipynb
  docs/source/indepth_tutorial/dps_lake_model.py
  docs/source/indepth_tutorial/general-introduction.ipynb
  docs/source/indepth_tutorial/open-exploration.ipynb
  ema_workbench/analysis/b_and_w_plotting.py
  ema_workbench/analysis/feature_scoring.py
  ema_workbench/analysis/pairs_plotting.py
  ema_workbench/analysis/parcoords.py
  ema_workbench/analysis/plotting.py
  ema_workbench/analysis/plotting_util.py
  ema_workbench/analysis/prim.py
  ema_workbench/analysis/prim_util.py
  ema_workbench/analysis/scenario_discovery_util.py
  ema_workbench/connectors/excel.py
  ema_workbench/connectors/pysd_connector.py
  ema_workbench/connectors/vensim.py
  ema_workbench/em_framework/ema_ipyparallel.py
  ema_workbench/em_framework/model.py
  ema_workbench/em_framework/optimization.py
  ema_workbench/em_framework/outcomes.py
  ema_workbench/em_framework/parameters.py
  ema_workbench/em_framework/points.py
  ema_workbench/examples/eijgenraam_example.py
  ema_workbench/examples/flu_timeseries_clustering.py
  ema_workbench/examples/lake_model_dps.py
  ema_workbench/examples/lake_model_dps_robust.py
  ema_workbench/examples/lake_model_sample_jointly.py
  ema_workbench/examples/lookup_example.py
  ema_workbench/examples/models/predatorPreyNetlogo/Wolf Sheep Predation.nlogo
  ema_workbench/examples/outputspace_exploration_lakeproblem.ipynb
  ema_workbench/examples/scenario_discovery.ipynb
  ema_workbench/examples/scenario_discovery_resampling.ipynb
  ema_workbench/examples/vadere_demo.ipynb
  test/test_analysis/test_cart.py
  test/test_analysis/test_parcoords.py
  test/test_analysis/test_prim.py
  test/test_em_framework/test_ema_ipyparallel.py
  test/test_em_framework/test_evaluators.py
  test/test_em_framework/test_util.py
  todo.md
Labels: docs, maintenance

#211 Replace deprecated `saltelli` with `sobol` SALib 1.4.6+.
  ema_workbench/em_framework/salib_samplers.py
  pyproject.toml
Labels: maintenance, dependency

#212 Add Dependabot configuration for GitHub Actions update check
  .github/dependabot.yml
Labels: ci, ignore-for-release, meta
