Repository quaquel/EMAworkbench, pull requests merged in 2022-09, with the labels that each got.

#160 __init__.py: Bump version to 2.3.0-dev
  ema_workbench/__init__.py
Labels: maintenance

#162 Create initial CONTRIBUTING.md documentation
  CONTRIBUTING.md
Labels: docs

#161 switch to using format string in prim logging
  ema_workbench/analysis/prim.py
Labels: bug, enhancement

#165 Put category emojis before text in release notes generation configuration
  .github/release.yml
Labels: docs, ignore-for-release

#169 Replace depreciated `shade` keyword in Seaborn kdeplot with `fill`
  ema_workbench/analysis/logistic_regression.py
Labels: dependency

#173 Create Read the Docs yaml configuration
  .readthedocs.yaml
  pyproject.toml
Labels: docs, ci

#174 CI: Add pip depencency caching, don't run on doc changes, update setup-python to v4
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: ci, maintenance

#180 [pre-commit.ci] auto fixes from pre-commit.com hooks
  .coveragerc
  .github/release.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/source/api_index.rst
  docs/source/basic_tutorial.rst
  docs/source/changelog.md
  docs/source/ema_documentation/glossary.rst
  docs/source/indepth_tutorial/.ipynb_checkpoints/dps_lake_model-checkpoint.py
  docs/source/index.rst
  docs/source/overview.rst
  docs/source/vensim-tips-and-tricks.rst
  docs/source/ystatic/sphinx doc tudelft style.css
  docs/source/ytemplates/layout.html
  ema_workbench/connectors/excel.py
  ema_workbench/connectors/netlogo.py
  ema_workbench/connectors/vadere.py
  ema_workbench/em_framework/evaluators.py
  ema_workbench/examples/lake_model_dps.py
  ema_workbench/examples/lake_model_dps_robust.py
  ema_workbench/examples/models/flu/mdl.c
  ema_workbench/examples/models/pysd/Teacup.mdl
  ema_workbench/examples/models/vensim example/model.mdl
  test/models/Sales_Agent_Market_Building_Dynamics.mdl
  test/models/Sales_Agent_Motivation_Dynamics.mdl
  test/models/Teacup.mdl
  todo.md
Labels: maintenance, ignore-for-release

#170 Output space exploration
  docs/source/api_index.rst
  docs/source/ema_documentation/em_framework/outputspace_exploration.rst
  ema_workbench/__init__.py
  ema_workbench/em_framework/__init__.py
  ema_workbench/em_framework/evaluators.py
  ema_workbench/em_framework/optimization.py
  ema_workbench/em_framework/outputspace_exploration.py
  ema_workbench/examples/lake_model_outputspace_exploration.py
  ema_workbench/examples/outputspace_exploration_lakeproblem.ipynb
  ema_workbench/util/ema_logging.py
  pyproject.toml
  test/test_em_framework/test_outputspace_exploration.py
  todo.md
Labels: feature

#182 Add unittest and coverage files to `.gitignore`
  .gitignore
Labels: maintenance, ignore-for-release

#183 update to outcomes documentation
  ema_workbench/em_framework/outcomes.py
Labels: docs

#186 CI: Let pre-commit update itself weekly
  .github/workflows/pre-commit-update.yml
  .pre-commit-config.yaml
Labels: ci, ignore-for-release
