Repository quaquel/EMAworkbench, pull requests merged in 2023-06, with the labels that each got.

#278 docs/examples: Always use n_processes=-1 in MultiprocessingEvaluator
  docs/source/examples/vadere_demo.ipynb
  docs/source/indepth_tutorial/open-exploration.ipynb
  ema_workbench/examples/example_eijgenraam.py
  ema_workbench/examples/example_netlogo.py
  ema_workbench/examples/example_vensim_advanced_flu.py
  ema_workbench/examples/vadere_demo.ipynb
Labels: docs

#282 Enhancement for #271: raise exception
  ema_workbench/em_framework/samplers.py
Labels: enhancement

#280 bugfix for #277 : load_results properly handles experiments dtypes
  ema_workbench/util/utilities.py
  test/data/test.tar.gz
  test/test_util/test_utilities.py
Labels: bug, testing

#283 docs: Add 2.4.1 changelog to master branch
  CHANGELOG.md
Labels: docs, ignore-for-release
