Repository quaquel/EMAworkbench, pull requests merged in 2023-12, with the labels that each got.

#317 inspect multiple boxes and display them in a single figure
  ema_workbench/analysis/prim.py
  ema_workbench/analysis/scenario_discovery_util.py
  ema_workbench/examples/sd_prim_flu.py
  test/data/test.tar.gz
  test/test_analysis/test_prim.py
  test/test_analysis/test_scenario_discovery_util.py
Labels: feature

#334 Replace deprecated zmq.eventloop.ioloop with Tornado's ioloop
  ema_workbench/em_framework/futures_ipyparallel.py
Labels: maintenance, dependency

#336 make workbench compatible with latest version of pysd
  ema_workbench/connectors/pysd_connector.py
  ema_workbench/examples/example_pysd_teacup.py
  ema_workbench/examples/models/pysd/Teacup.py
Labels: bug

#339 bugfixes for string vs bytestring
  ema_workbench/connectors/vensimDLLwrapper.py
Labels: bug

#342 Fix htmltheme of docs
  docs/source/conf.py
Labels: docs

#328 [WIP] MPI update
  .github/workflows/ci.yml
  docs/source/indepth_tutorial/mpi-evaluator.ipynb
  ema_workbench/em_framework/__init__.py
  ema_workbench/em_framework/evaluators.py
  ema_workbench/em_framework/futures_ipyparallel.py
  ema_workbench/em_framework/futures_mpi.py
  ema_workbench/examples/example_mpi_lake_model.py
  ema_workbench/examples/slurm_script.sh
  ema_workbench/examples/test.tar.gz
  test/test_em_framework/test_futures_mpi.py
Labels: enhancement, performance

#343 Update version to 2.5.0 and update release notes
  CHANGELOG.md
  ema_workbench/__init__.py
Labels: ignore-for-release
