Repository quaquel/EMAworkbench, pull requests merged in 2023-04, with the labels that each got.

#235 bugfixes to flu_example.py
  ema_workbench/examples/flu_example.py
Labels: bug

#249 Parallexaxis doc
  ema_workbench/analysis/parcoords.py
Labels: docs

#232 callbacks: Improve performance of _store_outcomes by ~35x
  ema_workbench/em_framework/callbacks.py
  test/test_em_framework/test_callback.py
Labels: enhancement, performance

#255 Fix pretty print for RealParameter and IntegerParameter
  ema_workbench/em_framework/parameters.py
Labels: bug

#256 __init__.py: Set version to 2.4.0 for release
  CHANGELOG.md
  ema_workbench/__init__.py
Labels: ignore-for-release

#257 __init__.py: Set version to 2.5.0-dev
  CHANGELOG.md
  ema_workbench/__init__.py
Labels: ignore-for-release

#259 Drop Python 3.8 support, require 3.9+
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  docs/source/getting_started/installation.rst
  pyproject.toml
Labels: docs, ci, maintenance

#242 readthedocs: Add search ranking and use latest Python version
  .readthedocs.yaml
  docs/requirements.txt
  docs/source/conf.py
  pyproject.toml
Labels: docs

#265 bugfix introduced by #241 in general-introduction from docs
  docs/source/indepth_tutorial/general-introduction.ipynb
Labels: bug, docs
