Repository quaquel/EMAworkbench, pull requests merged in 2023-02, with the labels that each got.

#221 CI: Timeout build job after 20 minutes
  .github/workflows/ci.yml
Labels: ci, ignore-for-release

#224 fixes broken link to installation instructions
  README.md
Labels: bug

#220 Docs: Fix developer installation commands by removing a space
  docs/source/getting_started/installation.rst
Labels: bug, docs
