Repository quaquel/EMAworkbench, pull requests merged in 2023-03, with the labels that each got.

#227 Fix Matplotlib and SciPy deprecations
  ema_workbench/analysis/b_and_w_plotting.py
  ema_workbench/analysis/scenario_discovery_util.py
Labels: maintenance

#228 fixes a bug where Prim modifies the experiments array
  ema_workbench/analysis/prim.py
Labels: bug

#229 optional preallocation in callback based on outcome shape and type
  ema_workbench/em_framework/callbacks.py
  ema_workbench/em_framework/outcomes.py
  test/test_em_framework/test_callback.py
  test/test_em_framework/test_outcomes.py
Labels: feature

#230 CI: Set the timeout specifically for the pytest step
  .github/workflows/ci.yml
Labels: ci, ignore-for-release

#234 bugfix for warning on number of processes and max_processes
  ema_workbench/em_framework/evaluators.py
Labels: bug
