Repository quaquel/EMAworkbench, pull requests merged in 2023-11, with the labels that each got.

#306 Speed up of plot_discrete_cdfs by 2 orders of magnitude
  ema_workbench/analysis/regional_sa.py
  ema_workbench/examples/regional_sa_flu.py
Labels: bug, enhancement, performance

#300 em_framework: Improve log messages, warning and errors
  ema_workbench/connectors/vensim.py
  ema_workbench/em_framework/callbacks.py
  ema_workbench/em_framework/ema_multiprocessing.py
  ema_workbench/em_framework/evaluators.py
  ema_workbench/em_framework/experiment_runner.py
  ema_workbench/em_framework/model.py
  ema_workbench/em_framework/optimization.py
  ema_workbench/em_framework/outcomes.py
  ema_workbench/em_framework/outputspace_exploration.py
  ema_workbench/em_framework/parameters.py
  ema_workbench/em_framework/points.py
  ema_workbench/em_framework/samplers.py
  ema_workbench/em_framework/util.py
Labels: enhancement

#313 analysis: Improve log messages, warning and errors
  ema_workbench/analysis/b_and_w_plotting.py
  ema_workbench/analysis/cart.py
  ema_workbench/analysis/feature_scoring.py
  ema_workbench/analysis/pairs_plotting.py
  ema_workbench/analysis/plotting.py
  ema_workbench/analysis/plotting_util.py
  ema_workbench/analysis/prim.py
Labels: enhancement

#315 fixes a bug where binomtest fails because of floating point math
  .pre-commit-config.yaml
  ema_workbench/analysis/prim.py
  ema_workbench/analysis/prim_util.py
  test/test_analysis/test_prim.py
Labels: bug
